SELECT DISTINCT SC7.C7_FILIAL FILIAL,SC7.C7_NUM NUMERO_PEDIDO,SYS_USR.USR_NOME USUARIO_PENDENTE FROM SC7010 SC7 

INNER JOIN SCR010 SCR
ON  SCR.D_E_L_E_T_ = SC7.D_E_L_E_T_
AND SCR.CR_FILIAL = SC7.C7_FILIAL
AND TRIM(SCR.CR_NUM) = TRIM(SC7.C7_NUM)

INNER JOIN SYS_USR
ON SCR.CR_USER = SYS_USR.USR_ID

WHERE SC7.D_E_L_E_T_ = ' '

AND SCR.CR_FILIAL || TRIM(SCR.CR_NUM) IN (

	SELECT DISTINCT SCRX.CR_FILIAL || TRIM(SCRX.CR_NUM) 
	FROM SCR010 SCRX 
	WHERE SCRX.D_E_L_E_T_ = ' ' AND SCRX.CR_STATUS <> '03'

	)

AND SCR.CR_STATUS <> '03'

ORDER BY SC7.C7_FILIAL,SC7.C7_NUM